INSERT INTO activities_table (activity) VALUES ('{"name": "Watch 10 movies", "date": "2024-01-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Read 20 books", "date": "2024-05-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Take a vacation out of the country", "date": "2024-12-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Learn to play a new instrument", "date": "2024-07-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Do one kind deed a week without recognition", "date": "2024-01-31",  "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Save $1000", "date": "2024-01-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Save $2000", "date": "2024-03-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Save $1,000,000!", "date": "2024-04-01", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Become master of all space, time, and dimension", "date": "2024-12-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Build a React project", "date": "2023-12-31", "completed": false}');
INSERT INTO activities_table (activity) VALUES ('{"name": "Learn Frontend design", "date": "2024-07-31", "completed": false}');